# NUMPYS IN PYTHON

### Difference between List and NumPy

List :

* Mixed Data type allowed

* Slower performance

* Low memory efficiency

* Manual Loops 


NumPy Array :

* Same data type only allowed

* Much Faster

* High efficiency

* Vector Operations east and Fast

In [ ]:
#### installing Numpy

%pip install numpy

In [3]:
import numpy as np 

In [7]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3,4,"hello",3.5]
a

[1, 2, 3, 4, 'hello', 3.5]

In [10]:
np.array(a)

array(['1', '2', '3', '4', 'hello', '3.5'], dtype='<U32')

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

#List doesn't support Multi dimensions

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr = np.arange(1 , 11)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr = np.zeros((6,6))
arr

mat = np.ones((4,5))
mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr = np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
### RANDOM NUMBER GENERATION

np.random.rand(5) ## IN NORMALIZATION SO VALUES WILL BE BETWEEN 10 to 1

array([0.2289693 , 0.39526624, 0.08280277, 0.6560342 , 0.99225638])

In [33]:
np.random.randn(10)  ## STANDARDIZATION VALUE BETWEEN -3 and 3

array([-1.1107141 , -1.56572731, -0.55684233,  0.12227582, -1.7927178 ,
        0.82737823, -0.52795687, -1.42653709, -1.01003354,  1.87516685])

In [35]:
np.random.randint(10,20,10)

array([17, 16, 11, 10, 10, 11, 11, 18, 15, 15], dtype=int32)

In [ ]:
### ARRAY ATTRIBUTES -> No Bracket in Attributes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.shape

(3, 3)

In [38]:
arr.size

9

In [39]:
arr.dtype

dtype('int64')

In [41]:
### ARRAY METHODS -> Use Brackets

arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [ ]:
arr.sum() # This is Inbuilt

np.int64(45)

In [46]:
np.sum(arr,0) # Vertical Axis is 0 and Horizontal is 1

array([12, 15, 18])

In [47]:
arr.mean()

np.float64(5.0)

In [48]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax() # index of maximum element

np.int64(8)

In [51]:
arr.argmin() # Index of Minimum element

np.int64(0)

In [52]:
### RESHAPING AND RESIZING

In [54]:
arr =np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
arr =arr.reshape(6,5)

In [58]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## SLICING AND INDEXING IN NUMPY ARRAYS

In [60]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [62]:
print(arr[6])

17


In [64]:
arr[1:5] # SLICING

array([12, 13, 14, 15])

In [65]:
arr[:3]

array([11, 12, 13])

In [66]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
arr[3::2] #STEPS IN SLICING

array([14, 16, 18, 20])

In [70]:
### NUMPY INDEXING AND SLICING OF MATRIX

arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [72]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0] ## INDEXING OF ROWS

array([1, 2, 3, 4, 5])

In [76]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [79]:
arr[0,0]

np.int64(1)

In [81]:
arr[5,4]

np.int64(30)

In [84]:
arr[0,4]

np.int64(5)

In [85]:
# SLICING ROWS AND COLUMNS

arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [87]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [89]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [93]:
arr[3:5,1:4]

array([[17, 18, 19],
       [22, 23, 24]])

In [99]:
### BOOLEAN INDEXING

arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [100]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [101]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

## ARRAY/NUMPY OPERATIONS

In [105]:
## ARITHMETIC OPERATIONS

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10]) #You need  to have same size arrays 

In [108]:
arr2 =a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

In [109]:
arr3 = a1 - a2
arr3

array([-5, -5, -5, -5, -5])

In [110]:
arr4 = a1 * a2
arr4

array([ 6, 14, 24, 36, 50])

In [111]:
arr5 = a1/a2
arr5

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [112]:
arr6 = a1 // a2
arr6

array([0, 0, 0, 0, 0])

In [113]:
arr7 = a1 ** a2
arr7

array([      1,     128,    6561,  262144, 9765625])

### BROADCASTING

In [117]:
l = [10,20,30,40]
arr = np.array(l)

In [118]:
arr + 10

array([20, 30, 40, 50])

In [120]:
arr = arr * 10

In [122]:
arr = arr // 10
arr

array([1, 2, 3, 4])

In [124]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [127]:
arr2 = arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

### DEEP AND SHALLOW COPY

In [129]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [134]:
slice = a[:5]
slice  = slice * 10
slice

array([10, 20, 30, 40, 50])

In [137]:
a # NO CHANGES IN A  when performing slicing operations , THIS IS EXAMPLE IF SHALLOW COPY

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [138]:
b = a 
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a ## DEEP COPYING when copying to do shallow copy we use ,copy method

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [140]:
b = a.copy()

b[0] = 23

b

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a ## NO CHANGES IN A EVEN COPYING

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### MATRIX OPERATIONS

In [142]:
A = np.array([[1,2],[4,5]])
B = np.array([[5,6],[7,8]])

In [143]:
A

array([[1, 2],
       [4, 5]])

In [144]:
B

array([[5, 6],
       [7, 8]])

In [147]:
A * B ## MULTIPLIES WITH RESPECT TO INDEX LOCATIONS, THIS IS not how multiplication happens in Matrix

array([[ 5, 12],
       [28, 40]])

In [148]:
## Performing Matrix Multiplication 

C = A @ B
C

array([[19, 22],
       [55, 64]])

In [149]:
## ANOTHER WAY

np.dot(A,B)

array([[19, 22],
       [55, 64]])

In [152]:
np.transpose(A) # Transpose

array([[1, 4],
       [2, 5]])

In [153]:
A.T # Anotherway of Transpose

array([[1, 4],
       [2, 5]])

### ADVANCE ARRAY MANIPULATION

    HERE WE CANNOT USE MATRIX ADVANCE ARRAY MANIPULATION IS DONE ON VECTORS ONLY

In [156]:
a =  np.array([1,2,3,4])

In [157]:
b = np.array([5,6,7,8])

In [158]:
a

array([1, 2, 3, 4])

In [159]:
b

array([5, 6, 7, 8])

In [160]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [161]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [162]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### SPLITTING ARRAY

In [164]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [165]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [166]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [167]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [169]:
a = np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [170]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
