# PRACTISING THE NUMPY 

In [86]:
import numpy as np


In [87]:
## VALID SUDOKU 
s =  np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],
    
    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9],
])



In [88]:
a = np.sum(s,axis=1)


In [89]:
for i in a:
    if i != 45:
        print("Sudoku not Valid")
        break
print(" For ROWS ITS VALID SUDOKU")
        

 For ROWS ITS VALID SUDOKU


In [90]:
b = np.sum(s,axis = 0)

In [91]:
for i in b:
    if i != 45:
        print("Sudoku not Valid")
        break
print(" For COLUMNS ITS VALID SUDOKU")

 For COLUMNS ITS VALID SUDOKU


In [92]:
for i in range (0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [93]:
for i in range (0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


#### DATA FRAMES PROBLEMS AND EXERCISES

In [94]:
## Columns : Age, Math Marks , Science Marks
data = np.array([
    [18,95,78], #student 1
    [19,92,88], #student 2
    [17,76,95], #student 3
    [18,65,70], #student 4
    [20,90,85]  #student 5
])

In [95]:
## GET THE SHAPE OF MATRIX

data.shape

(5, 3)

In [96]:
## FIND THE AVERAGE AGE OF STUDENTS

age = np.mean(data[:,0])
print(age)


18.4


In [97]:
## MATHS MARKS OF ALL STUDENTS
data[:,1]   

array([95, 92, 76, 65, 90])

In [98]:
## HIGHEST SCIENCE MARKS

sc_max = np.max(data[:,2])
print(sc_max)

95


In [99]:
## DETAILS OF THE STUDENT WHO HAVE SCORED MORE THAN 90 IN MATHS

data[data[:,1] > 90]

array([[18, 95, 78],
       [19, 92, 88]])

In [100]:
## INCREASE MATHS MARKS OF ALL STUDENTS BY 5

data[:,1] += 5

data


array([[ 18, 100,  78],
       [ 19,  97,  88],
       [ 17,  81,  95],
       [ 18,  70,  70],
       [ 20,  95,  85]])

In [101]:
## FIND HOW MANY STUDENTS ARE YOUNGER THAN 19

len(data[data[:,0]<19])

3

In [102]:
## CALCULATE THE AVERAGE MARKS IN EACH SUBJECT COLUMN VISE MEAN

np.mean(data[:,1:], axis=0)

array([88.6, 83.2])

In [103]:
## GET DATA OF STUDENTS WHO SCORES AT LEAST 80 IN BOTH SUBJECTS

data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [104]:
data

array([[ 18, 100,  78],
       [ 19,  97,  88],
       [ 17,  81,  95],
       [ 18,  70,  70],
       [ 20,  95,  85]])

In [105]:
### REPLACE ALL SCIENCE LESS THAN 75 to ZERO

data[:,2][data[:,2]<75] = 0

data

array([[ 18, 100,  78],
       [ 19,  97,  88],
       [ 17,  81,  95],
       [ 18,  70,   0],
       [ 20,  95,  85]])